Dependency removed
systers/PCSA-Android pull request #303
Opened 2016-11-20 16:14 UTC by codingblazer

#302 
I have made the following changes -

1.Removed dependency 'com.github.paolorotolo:appintro:1.4.0'.
2.Removed files CircleIntro.java , FirstSlide, SecondSlide , ThirdSlide , FourthSlide.java and added CircleIntroActivity (Intro using Viewpager)
 
UI is not changed (checked on multiple devices).

2016-11-26 11:03 UTC, sandarumk requested changes
Please add meaning full name for variables. The rest seem to be fine.

2016-11-26 11:03 UTC, sandarumk commented on app/src/main/java/com/peacecorps/pcsa/circle_of_trust/slides/CircleIntroActivity.java
> +    public class MyViewPagerAdapter extends PagerAdapter {
Do not use names like this for classes.

2016-11-26 11:08 UTC, codingblazer commented on app/src/main/java/com/peacecorps/pcsa/circle_of_trust/slides/CircleIntroActivity.java
> +    public class MyViewPagerAdapter extends PagerAdapter {
@sandarumk Thanks for review. I will make the requested changes.

2016-11-26 12:35 UTC, codingblazer commented
@sandarumk I have changed the variable names and made comments wherever necessary.

2016-12-08 11:12 UTC, sandarumk commented
@codingblazer Please add a meaningful commit messages.

2016-12-08 11:52 UTC, codingblazer commented
@sandarumk Sorry about that. I have changed the commit message.

2016-12-10 03:39 UTC, sandarumk commented
Please follow the guidelines of the repository when you submit a PR. You can find them in the Wiki. The links to the specific articles are in the READ ME file.

2016-12-10 07:44 UTC, codingblazer commented
@sandarumk Thanks for reference. I have read all the rules now and will adhere to them in future. Do you want me to change comments in this PR or anything else also.

2016-12-10 07:47 UTC, sandarumk commented
Yes I need to change the comments in this PR.

2016-12-10 07:48 UTC, sandarumk requested changes

2016-12-10 07:48 UTC, sandarumk commented on app/src/main/java/com/peacecorps/pcsa/circle_of_trust/slides/CircleIntroActivity.java
> +    /**
Follow the method commenting format. You can refer the Wiki if you need the format.

2016-12-10 07:48 UTC, sandarumk commented on app/src/main/java/com/peacecorps/pcsa/circle_of_trust/slides/CircleIntroActivity.java
> +public class CircleIntroActivity extends AppCompatActivity {
Follow the class commenting format to add the header comments. Refer the wiki if you need the format

2016-12-10 09:03 UTC, codingblazer commented
@sandarumk I have added the class and method comments.

2016-12-10 09:14 UTC, merged

2016-12-18 19:13 UTC, codingblazer commented
@sandarumk I just noticed that there are two "Done" on the following screen and both of them were clickable before this PR. I didn't noticed it that time because I assumed "Done" (TextView) is just for indication. I am very sorry for that.
![whatsapp image 2016-12-19 at 00 42 00](https://cloud.githubusercontent.com/assets/13872065/21295856/14b607ba-c584-11e6-8689-89e224c5ea03.jpeg)

Should I commit implementation of this "Done" (TextView) to this PR only or create separate one.

2016-12-19 02:33 UTC, sandarumk commented
Can you open another issue stating the same. Then let's discuss there separately.