Fixes Issue #388 Added better image in third intro of Circle of Trust
systers/PCSA-Android pull request #401
Opened 2017-03-04 19:44 UTC by madhavrathi

New Look :- 
![new](https://cloud.githubusercontent.com/assets/22375731/23581764/13095dce-0141-11e7-9936-239b5199a065.png)

2017-03-08 22:44 UTC, madhavrathi commented
@sandarumk  Please review this.

2017-03-12 07:43 UTC, sandarumk requested changes

2017-03-12 07:43 UTC, sandarumk commented on app/app.iml
>        <sourceFolder url="file://$MODULE_DIR$/src/test/jni" isTestSource="true" />
This should not be in version control

2017-03-12 08:55 UTC, sandarumk requested changes

2017-03-12 08:55 UTC, sandarumk commented on app/app.iml
>        <sourceFolder url="file://$MODULE_DIR$/src/test/assets" type="java-test-resource" />
It is still here. Please remove app.iml file.

2017-03-12 09:05 UTC, madhavrathi commented on app/app.iml
>        <sourceFolder url="file://$MODULE_DIR$/src/test/assets" type="java-test-resource" />
Please help me out here. How do i remove app.iml file from my commit ?

2017-03-12 14:11 UTC, sandarumk commented on app/app.iml
>        <sourceFolder url="file://$MODULE_DIR$/src/test/assets" type="java-test-resource" />
This should do the trick. Next time when committing make sure not to add it. http://stackoverflow.com/questions/2047465/how-can-i-delete-a-file-from-git-repo
If you face a problem, a quick google search should help. There are plenty of related questions in Stack Overflow. Once you add the commit, try to squash your commits so it should appear as one. If not at least remove the app.iml fie then I will squash your commits when merging.

2017-03-13 04:01 UTC, sandarumk commented
Did you remove the existing low quality image?

2017-03-13 04:15 UTC, madhavrathi commented
@sandarumk Not yet, should I ?

2017-03-13 05:03 UTC, sandarumk commented
yes.

2017-03-13 05:34 UTC, madhavrathi commented
@sandarumk i have now solved everything you asked for and made them into single commit. Sorry for the Delay

2017-03-13 05:57 UTC, sandarumk commented
Sorry I forgot this earlier.
https://developer.android.com/guide/practices/screens_support.html

2017-03-13 14:51 UTC, madhavrathi commented
@sandarumk  i didn't get your point

2017-03-13 15:03 UTC, sandarumk commented
Did you read the article on the link?

2017-06-06 01:58 UTC, closed without merging